package com.example.demo.core.domain.enums;

public enum Strategie {
    DONNANTDONNANT,
    RANCUNIER,
    TOUJOURSCOOPERER,
    TOUJOURSTRAHIR,
    ALEATOIRE,
    DONNANTDONNANTALEATOIRE,
    DONNANTPOURDEUXDONNANTALEATOIRE,
    DONNANTDONNANTSOUPCONNEUX,
    DONNANTPOURDEUXDONNANT,
    PACIFICATEURNAIF,
    SONDEURNAIF,
    GRADUEL, SONDEURREPENTANT
}
