package fr.uga.miage.m1.my_projet_g1_10.enums;

public enum Strategie {
    DONNANTDONNANT,
    RANCUNIER,
    TOUJOURSCOOPERER,
    TOUJOURSTRAHIR,
    ALEATOIRE,
    DONNANTDONNANTALEATOIRE,
    DONNANTPOURDEUXDONNANTALEATOIRE,
    DONNANTDONNANTSOUPCONNEUX,
    DONNANTPOURDEUXDONNANT,
    PACIFICATEURNAIF,
    SONDEURNAIF,
    GRADUEL, SONDEURREPENTANT
}
